### ISSUE TITLE
rename project to react-typescript-express-starter-kit

### ISSUE THREAD

**Issue by tommysullivan** [bob-bins/react-typescript-express-starter-kit#11]
Can we use this as a sort of "skeleton" and then build other apps on top of it? such as your resume. we can build your resume on top of this in its own repo after we get the skeleton up and running?

I already renamed my fork to react-typescript-express-starter-kit

**Comment by bob-bins** [comment]
yeah I was actually gonna suggest that as well since we seem to be branching from the original idea. but in a good way - this is way more fun
